# Generated by Django 4.0.1 on 2022-01-09 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_categoria_created_categoria_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='created',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='updated',
        ),
    ]
